### ISSUE TITLE
Implement Leader() and Resign()

### ISSUE THREAD

**Issue by danl5** [danl5/goelect#13]
`Leader` returns the information of the current cluster's leader
`Resign` triggers a re-election

**Comment by danl5** [comment]
Leader:
https://github.com/danl5/goelect/commit/de4936aecbce062658f95a08c5d2b5c14f9d610f

**Comment by fubss** [comment]
Please clarify why `Resign` func was not implemented? 

It seems useful in case something went wrong with the the leader outside the goelect package, and we need run election again before timeout expires

**Comment by danl5** [comment]
> Please clarify why `Resign` func was not implemented?
> 
> It seems useful in case something went wrong with the the leader outside the goelect package, and we need run election again before timeout expires

Hi @fubss , thank you for your suggestion. In fact, I later realized that:
- the heartbeat timeout can be set small enough (default is 300 milliseconds), allowing for automatic and quick switching when the leader fails. 
- To implement `Resign`, it still needs to rely on the heartbeat timeout mechanism, which theoretically doesn't shorten the switching time.

Implementing `TransferLeaderTo `might be more valuable than `Resign`, but the complexity of this feature is relatively high and requires some time, so it hasn't been implemented for now.
