### ISSUE TITLE
your own rpc implementation

### ISSUE THREAD

**Issue by farwydi** [danl5/goelect#18]
proposal to give the opportunity to use your own rpc implementation

via interface?

**Comment by danl5** [comment]
Didn't quite get it, do you mean to expose the rpc implementation in this project, or to abstract the rpc process to make it easier to add other implementations?

**Comment by farwydi** [comment]
I meant abstracting the RPC process to accommodate different environments and constraints, like closed environments requiring additional security measures such as MTLS. This would provide users with the flexibility to use their own RPC implementations via a standardized interface.

**Comment by danl5** [comment]
Of course, the previous consideration is that RPC is currently only used to transfer data of the control plane, the requirements for data security are not so high, and should be user-agnostic, so the process of intra-cluster communication is not open to users.
But now we can schedule this matter :)

**Comment by danl5** [comment]
Hi @farwydi , not sure if you're interested in reviewing this PR #23 . It abstracts the transport layer, as we discussed above.

**Comment by danl5** [comment]
Done.  #23
